### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Super Admin",
  "username": "superadm",
  "password": "SuperAdmin1234!",
  "email": "superadmin@example.com"
}


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "password": "SuperAdmin1234!",
  "email": "superadmin@example.com" 
}

### Get User Profile (Requires Authentication)
GET http://localhost:3000/users/profile
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Update User Profile (Requires Authentication) not working
PUT http://localhost:3000/users/profile 
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

{
  "fullName": "Super Admin",
  "username": "superadmin",
  "password": "SuperAdmin1234!",
  "email": "superadmin@example.com" 
}

### Logout User (Requires Authentication)
POST http://localhost:3000/auth/logout
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get All Users (Requires Authentication)
GET http://localhost:3000/users
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By ID (Requires Authentication)
GET http://localhost:3000/users/SM-00001
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Delete User By ID (Requires Authentication)
DELETE http://localhost:3000/users/
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By Username (Requires Authentication)
GET http://localhost:3000/users/username/superadmin
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By Email (Requires Authentication)
GET http://localhost:3000/users/email/email validation
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get Users By Role (Requires Authentication)
GET http://localhost:3000/users/role/admin3
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Delete All Users (Requires Authentication)
DELETE http://localhost:3000/users
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Update User By ID (Requires Authentication)
PUT http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

{
 "fullName": "Super Admin",
 "role": "SUPERADMIN"
}

