### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  
  "fullName": "Stephen Mwangi",
  "username": "stephen",
  "email": "stephen@example.com",
  "password": "Stephen1234!"

  

}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "stephen@example.com",
  "password": "Stephen1234!"
}

### Get User Profile (Requires Authentication)
GET http://localhost:3000/users/profile
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Update User Profile (Requires Authentication) not working
PUT http://localhost:3000/users/profile 
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

{
  "user_id": "usr_1001",
    "firstName": "Super",
    "lastName": "Admin",
    "username": "superadmin",
    "email": "superadmin@example.com"
}

### Logout User (Requires Authentication)
POST http://localhost:3000/auth/logout
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get All Users (Requires Authentication)
GET http://localhost:3000/users
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By ID (Requires Authentication)
GET http://localhost:3000/users/usr_1003
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Delete User By ID (Requires Authentication)
DELETE http://localhost:3000/users
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By Username (Requires Authentication)
GET http://localhost:3000/users/username/kennedy
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get User By Email (Requires Authentication)
GET http://localhost:3000/users/email/:email
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Get Users By Role (Requires Authentication)
GET http://localhost:3000/users/role/:role
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Delete All Users (Requires Authentication)
DELETE http://localhost:3000/users
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

### Update User By ID (Requires Authentication)
PUT http://localhost:3000/users/:user_id
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN  # Replace YOUR_ACCESS_TOKEN

{
  "firstName": "Updated",
  "lastName": "User",
  "username": "updated_username",
  "email": "updated@example.com",
  "avatar": "updated_avatar.png",
  "role": "admin"
}

